library ieee;
use ieee.std_logic_1164.all;
entity id_ex_reg is 
    port(
        clk,rst, enable:in std_logic; 
        immediate_d: in std_logic_vector(31 downto 0);
        immediate_q: out std_logic_vector(31 downto 0);
        pc1_d: in std_logic_vector(31 downto 0);
        pc1_q: out std_logic_vector(31 downto 0);
        inputport_d:in std_logic_vector(31 downto 0);
        inputport_q:out std_logic_vector(31 downto 0);
        readdata1_d:in std_logic_vector(31 downto 0);
        readdata1_q:out std_logic_vector(31 downto 0);
        readdata2_d:in std_logic_vector(31 downto 0);
        readdata2_q:out std_logic_vector(31 downto 0);
        writeaddress1_d: in std_logic_vector(2 downto 0);
        writeaddress1_q:out std_logic_vector(2 downto 0);
        writeaddress2_d: in std_logic_vector(2 downto 0);
        writeaddress2_q:out std_logic_vector(2 downto 0);
        memtoreg_q: out std_logic;
        memtoreg_d:in std_logic;
        outputenable_q: out std_logic;
        outputenable_d:in std_logic;
        regwrite1_q: out std_logic;
        regwrite1_d:in std_logic;
        regwrite2_q: out std_logic;
        regwrite2_d:in std_logic;
        inputenable_q:out std_logic;
        inputenable_d:in std_logic;
        memwrite_q:out std_logic;
        memwrite_d:in std_logic;
        mem_add_src_q: out std_logic;
        mem_add_src_d: in std_logic;
        mem_data_src_q: out std_logic;
        mem_data_src_d: in std_logic;
        sp_dec_q: out std_logic;
        sp_dec_d: in std_logic;
        pc_src_q: out std_logic;
        pc_src_d: in std_logic;
        alu_control_q: out std_logic_vector(2 downto 0);
        alu_control_d: in std_logic_vector(2 downto 0);
        alu_src_q: out std_logic;
        alu_src_d: in std_logic;
        branch_q: out std_logic;
        branch_d: in std_logic;
        branch_type_q: out std_logic_vector(1 downto 0);
        branch_type_d: in std_logic_vector(1 downto 0);
        inc_sp_q: out std_logic;
        inc_sp_d: in std_logic;
        set_carry_q: out std_logic;
        set_carry_d: in std_logic;
        ccr_store_q: out std_logic;
        ccr_store_d: in std_logic;
        ccr_restore_q: out std_logic;
        ccr_restore_d: in std_logic;
        flag_enable_q: out std_logic;
        flag_enable_d: in std_logic
        );
end id_ex_reg;
architecture dff of id_ex_reg is
begin 
process(clk,rst)
begin
    if(rst='1')then
        inputport_q<=(others=>'0');
        immediate_q<=(others=>'0');
        pc1_q<=(others=>'0');
        readdata1_q<=(others=>'0');
        readdata2_q<=(others=>'0');
        writeaddress2_q<=(others=>'0');
        writeaddress1_q<=(others=>'0');
        memtoreg_q<='0';
        outputenable_q<='0';
        regwrite1_q<='0';
        regwrite2_q<='0';
        inputenable_q<='0';
        memwrite_q<='0';
        mem_add_src_q<='0';
        mem_data_src_q<='0';
        sp_dec_q<='0';
        pc_src_q<='0';
        alu_control_q<=(others=>'0');
        alu_src_q<='0';
        branch_q<='0';
        branch_type_q<=(others=>'0');
        inc_sp_q<='0';
        set_carry_q<='0';
        ccr_store_q<='0';
        ccr_restore_q<='0';
        flag_enable_q<='0';
    elsif clk'event and clk = '1' and enable = '1' then 
        inputport_q<=inputport_d;
        immediate_q<=immediate_d;
        pc1_q<=pc1_d;
        readdata1_q<=readdata1_d;
        readdata2_q<=readdata2_d;
        writeaddress2_q<=writeaddress2_d;
        writeaddress1_q<=writeaddress1_d;
        memtoreg_q<=memtoreg_d;
        outputenable_q<=outputenable_d;
        regwrite1_q<=regwrite1_d;
        regwrite2_q<=regwrite2_d;
        inputenable_q<=inputenable_d;
        memwrite_q<=memwrite_d;
        mem_add_src_q<=mem_add_src_d;
        mem_data_src_q<=mem_data_src_d;
        sp_dec_q<=sp_dec_d;
        pc_src_q<=pc_src_d;
        alu_control_q<=alu_control_d;
        alu_src_q<=alu_src_d;
        branch_q<=branch_d;
        branch_type_q<=branch_type_d;
        inc_sp_q<=inc_sp_d;
        set_carry_q<=set_carry_d;
        ccr_store_q<=ccr_store_d;
        ccr_restore_q<=ccr_restore_d;
        flag_enable_q<=flag_enable_d;
    end if;
end process;
end dff; 